spring:
  config:
    name: prac
  datasource:
    url: jdbc:postgresql://localhost:7654/medicamentdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql:
server:
  port: 7979
  error:
    include-message: always
    include-exception: true

token:
  signing:
    key: 96412781eb036f4ceef009298a756969baf197f4d6e9b99287b671581b65da7b